"""
api/routers/reports.py
======================
Endpoints for Allure report data, execution evidence (GIF/video),
disk usage and cleanup.

GET  /api/reports/orchestrator-summary
GET  /api/reports/gherkin-results
GET  /api/reports/attachment/{filename}
GET  /api/reports/usage
POST /api/reports/clean
GET  /api/execution/{execution_id}/gif
GET  /api/execution/{execution_id}/video
"""
from __future__ import annotations

import glob
import io
import json
import os
import shutil
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, StreamingResponse

from api.config import ALLURE_REPORT, ALLURE_RESULTS, PROJECT_ROOT
from api.models import CleanRequest

router = APIRouter(tags=["Reports"])


# ── Helper ─────────────────────────────────────────────────────────────────────

def find_gif_execution_id(scenario_name: str, start_time_ms: int) -> Optional[str]:
    """
    Intenta encontrar un directorio en reports/temp_gif que coincida
    con el nombre del escenario y el timestamp de inicio.
    """
    try:
        temp_gif_dir = PROJECT_ROOT / "reports" / "temp_gif"
        if not temp_gif_dir.exists():
            return None

        timestamp_sec  = int(start_time_ms / 1000)
        sanitized_name = "".join([c if c.isalnum() else "_" for c in scenario_name])
        dirs           = os.listdir(str(temp_gif_dir))

        expected_prefix = f"{timestamp_sec}_{sanitized_name}"
        if expected_prefix in dirs:
            return expected_prefix

        for d in dirs:
            if d.endswith(f"_{sanitized_name}"):
                try:
                    dir_ts = int(d.split("_")[0])
                    if abs(dir_ts - timestamp_sec) <= 5:
                        return d
                except (ValueError, IndexError):
                    continue
        return None
    except Exception:
        return None


# ── Report routes ──────────────────────────────────────────────────────────────

@router.get("/api/reports/orchestrator-summary", tags=["Reports"])
def get_orchestrator_summary():
    """Return the summary JSON generated by orchestrator.py."""
    summary_file = ALLURE_RESULTS.parent / "orchestrator_summary.json"
    if not summary_file.exists():
        return {"test_cycles": []}
    try:
        with open(summary_file, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to read summary: {exc}")


@router.get("/api/reports/gherkin-results", tags=["Reports"])
def get_gherkin_results():
    """
    Parsea los archivos JSON de resultados de Allure para extraer
    un listado estructurado de las pruebas Gherkin ejecutadas.
    """
    try:
        empty = {
            "features": [],
            "summary":  {"total": 0, "passed": 0, "failed": 0, "broken": 0, "skipped": 0, "total_duration_ms": 0},
        }
        if not ALLURE_RESULTS.exists():
            return empty

        result_files = glob.glob(str(ALLURE_RESULTS / "*-result.json"))
        if not result_files:
            return empty

        features_map: dict = {}
        summary = {"total": 0, "passed": 0, "failed": 0, "broken": 0, "skipped": 0, "total_duration_ms": 0}

        for result_file in result_files:
            try:
                with open(result_file, "r", encoding="utf-8") as f:
                    result_data = json.load(f)

                scenario_name = result_data.get("name", "Unknown Scenario")
                status        = result_data.get("status", "unknown")
                duration_ms   = 0
                if result_data.get("stop") and result_data.get("start"):
                    duration_ms = result_data["stop"] - result_data["start"]

                feature_name = "Unknown Feature"
                tags: list   = []
                for label in result_data.get("labels", []):
                    if label.get("name") == "feature":
                        feature_name = label.get("value", feature_name)
                    elif label.get("name") == "tag":
                        tv = label.get("value", "")
                        if tv:
                            tags.append(f"@{tv}" if not tv.startswith("@") else tv)

                steps_data: list = []
                for step in result_data.get("steps", []):
                    step_name   = step.get("name", "")
                    step_status = step.get("status", "unknown")
                    keyword     = ""
                    for kw in ["Given ", "When ", "Then ", "And ", "But "]:
                        if step_name.startswith(kw):
                            keyword   = kw.strip()
                            step_name = step_name[len(kw):]
                            break
                    attachments = [
                        {"name": a.get("name"), "source": a.get("source"), "type": a.get("type")}
                        for a in step.get("attachments", [])
                    ]
                    steps_data.append({"name": step_name, "keyword": keyword, "status": step_status, "attachments": attachments})

                if feature_name not in features_map:
                    features_map[feature_name] = []

                start_ms      = result_data.get("start", 0)
                original_name = result_data.get("pehape_original_name") or scenario_name
                display_name  = scenario_name
                gif_id        = find_gif_execution_id(original_name, start_ms)

                features_map[feature_name].append({
                    "name":          original_name,
                    "display_name":  display_name,
                    "status":        status,
                    "duration_ms":   duration_ms,
                    "start_ms":      start_ms,
                    "tags":          tags,
                    "steps":         steps_data,
                    "gifExecutionId": gif_id,
                })

                summary["total"] += 1
                summary["total_duration_ms"] += duration_ms
                if status in summary:
                    summary[status] += 1
            except Exception:
                continue

        features_list = []
        for fname, scenarios in sorted(features_map.items()):
            features_list.append({
                "name":      fname,
                "scenarios": sorted(scenarios, key=lambda s: s.get("start_ms", 0)),
            })

        return {"features": features_list, "summary": summary}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/reports/attachment/{filename}", tags=["Reports"])
def get_report_attachment(filename: str):
    """Sirve los archivos adjuntos (imágenes, json, etc) generados por Allure."""
    try:
        requested_path = (ALLURE_RESULTS / filename).resolve()
        if not str(requested_path).startswith(str(ALLURE_RESULTS.resolve())):
            raise HTTPException(status_code=403, detail="Acceso denegado")
        if not requested_path.exists():
            raise HTTPException(status_code=404, detail="Archivo no encontrado")
        return FileResponse(str(requested_path))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/reports/usage", tags=["Maintenance"])
def get_reports_usage():
    """Retorna el uso de disco de los directorios de reportes."""
    try:
        report_root       = PROJECT_ROOT / "reports"
        results_dir       = report_root / "allure_results"
        report_dir        = report_root / "allure-report"
        screenshots_dir   = report_root / "screenshots"

        def get_dir_size(path: Path) -> int:
            total = 0
            if path.exists():
                for entry in path.rglob("*"):
                    if entry.is_file():
                        total += entry.stat().st_size
            return total

        results_size     = get_dir_size(results_dir)
        report_size      = get_dir_size(report_dir)
        screenshots_size = get_dir_size(screenshots_dir)

        return {
            "results_size":     results_size,
            "report_size":      report_size,
            "screenshots_size": screenshots_size,
            "total_size":       results_size + report_size + screenshots_size,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/api/reports/clean", tags=["Maintenance"])
async def clean_reports(payload: CleanRequest):
    """
    Limpia los directorios de reportes.
    Body: { "target": "results" | "report" | "screenshots" | "all" }
    """
    try:
        target          = payload.target
        report_root     = PROJECT_ROOT / "reports"
        results_dir     = report_root / "allure_results"
        report_dir      = report_root / "allure-report"
        screenshots_dir = report_root / "screenshots"
        cleaned: list   = []

        if target in ("results", "all"):
            if results_dir.exists():
                shutil.rmtree(results_dir)
                results_dir.mkdir(parents=True, exist_ok=True)
                cleaned.append("Resultados Raw")

        if target in ("report", "all"):
            if report_dir.exists():
                shutil.rmtree(report_dir)
                report_dir.mkdir(parents=True, exist_ok=True)
                cleaned.append("Reporte Generado")

        if target in ("screenshots", "all"):
            if screenshots_dir.exists():
                shutil.rmtree(screenshots_dir)
                screenshots_dir.mkdir(parents=True, exist_ok=True)
                cleaned.append("Screenshots")

        if not cleaned:
            raise HTTPException(status_code=400, detail="Target inválido o nada que limpiar")

        return {"message": f"Se han limpiado: {', '.join(cleaned)}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Execution evidence ─────────────────────────────────────────────────────────

@router.get("/api/execution/{execution_id}/gif", tags=["Execution Plan"])
def get_execution_gif(execution_id: str):
    """Genera y sirve un GIF de la ejecución."""
    try:
        from PIL import Image, ImageDraw, ImageFont

        gif_source_dir = PROJECT_ROOT / "reports" / "temp_gif" / execution_id
        if not gif_source_dir.exists():
            raise HTTPException(status_code=404, detail="Execution data not found")

        images = sorted(glob.glob(str(gif_source_dir / "*.png")))
        if not images:
            raise HTTPException(status_code=404, detail="No images found for GIF")

        frames = []
        for index, image_path in enumerate(images):
            try:
                img = Image.open(image_path).convert('RGB')
                draw = ImageDraw.Draw(img)
                try:
                    font = ImageFont.truetype("arial.ttf", 36)
                except IOError:
                    font = ImageFont.load_default()
                text = f"#{index + 1}"
                x, y = 10, 10
                text_bbox = draw.textbbox((x, y), text, font=font)
                draw.rectangle(text_bbox, fill="black")
                draw.text((x, y), text, font=font, fill="white")
                frames.append(img)
            except Exception as ex:
                print(f"Error processing frame {image_path}: {ex}")

        if not frames:
            raise HTTPException(status_code=500, detail="Failed to process frames")

        output = io.BytesIO()
        frames[0].save(output, format="GIF", append_images=frames[1:], save_all=True, duration=1000, loop=0)
        output.seek(0)
        return StreamingResponse(
            output, 
            media_type="image/gif",
            headers={"Content-Disposition": f'attachment; filename="execution_{execution_id}.gif"'}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/execution/{execution_id}/video", tags=["Execution Plan"])
def get_execution_video(execution_id: str):
    """Genera y sirve un Video (MP4) de la ejecución."""
    try:
        import cv2
        import numpy as np
        import tempfile

        video_source_dir = PROJECT_ROOT / "reports" / "temp_gif" / execution_id
        if not video_source_dir.exists():
            raise HTTPException(status_code=404, detail="Execution data not found")

        images = sorted(glob.glob(str(video_source_dir / "*.png")))
        if not images:
            raise HTTPException(status_code=404, detail="No images found for Video")

        first_frame = cv2.imread(images[0])
        if first_frame is None:
            raise HTTPException(status_code=500, detail="Failed to read first frame")

        height, width, _ = first_frame.shape
        temp_video = tempfile.NamedTemporaryFile(delete=False, suffix='.mp4')
        temp_video_path = temp_video.name
        temp_video.close()

        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        base_fps = 1
        output_fps = 10
        repeat_count = output_fps // base_fps

        out = cv2.VideoWriter(temp_video_path, fourcc, output_fps, (width, height))
        if not out.isOpened():
            fourcc = cv2.VideoWriter_fourcc(*'avc1')
            out = cv2.VideoWriter(temp_video_path, fourcc, output_fps, (width, height))
        if not out.isOpened():
            raise HTTPException(status_code=500, detail="Failed to initialize video writer")

        for index, image_path in enumerate(images):
            try:
                frame = cv2.imread(image_path)
                if frame is None:
                    continue
                text = f"#{index + 1}"
                font = cv2.FONT_HERSHEY_SIMPLEX
                font_scale = 1.2
                thickness = 3
                (text_width, text_height), baseline = cv2.getTextSize(text, font, font_scale, thickness)
                x, y = 10, 10 + text_height
                cv2.rectangle(frame, (x - 5, y - text_height - 5), (x + text_width + 5, y + baseline + 5), (0, 0, 0), -1)
                cv2.putText(frame, text, (x, y), font, font_scale, (255, 255, 255), thickness)
                for _ in range(repeat_count):
                    out.write(frame)
            except Exception as ex:
                pass
        
        out.release()
        return FileResponse(
            temp_video_path, 
            media_type="video/mp4", 
            filename=f"execution_{execution_id}.mp4"
        )
    except ImportError:
        raise HTTPException(status_code=500, detail="OpenCV (cv2) is not installed. Install with: pip install opencv-python")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
